// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// as_coords
NumericVector as_coords(NumericVector object, int fmt);
RcppExport SEXP _Waypoint_as_coords(SEXP objectSEXP, SEXP fmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type object(objectSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    rcpp_result_gen = Rcpp::wrap(as_coords(object, fmt));
    return rcpp_result_gen;
END_RCPP
}
// convertcoords
NumericVector convertcoords(NumericVector x, int fmt);
RcppExport SEXP _Waypoint_convertcoords(SEXP xSEXP, SEXP fmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    rcpp_result_gen = Rcpp::wrap(convertcoords(x, fmt));
    return rcpp_result_gen;
END_RCPP
}
// latlon
NumericVector latlon(NumericVector cd, LogicalVector value);
RcppExport SEXP _Waypoint_latlon(SEXP cdSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cd(cdSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(latlon(cd, value));
    return rcpp_result_gen;
END_RCPP
}
// validatecoords
NumericVector validatecoords(NumericVector x, bool force);
RcppExport SEXP _Waypoint_validatecoords(SEXP xSEXP, SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(validatecoords(x, force));
    return rcpp_result_gen;
END_RCPP
}
// formatcoords
CharacterVector formatcoords(NumericVector x, bool usenames, bool validate, int fmt);
RcppExport SEXP _Waypoint_formatcoords(SEXP xSEXP, SEXP usenamesSEXP, SEXP validateSEXP, SEXP fmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type usenames(usenamesSEXP);
    Rcpp::traits::input_parameter< bool >::type validate(validateSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    rcpp_result_gen = Rcpp::wrap(formatcoords(x, usenames, validate, fmt));
    return rcpp_result_gen;
END_RCPP
}
// as_waypoints
DataFrame as_waypoints(DataFrame object, int fmt);
RcppExport SEXP _Waypoint_as_waypoints(SEXP objectSEXP, SEXP fmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type object(objectSEXP);
    Rcpp::traits::input_parameter< int >::type fmt(fmtSEXP);
    rcpp_result_gen = Rcpp::wrap(as_waypoints(object, fmt));
    return rcpp_result_gen;
END_RCPP
}
// bin
void bin();
RcppExport SEXP _Waypoint_bin() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    bin();
    return R_NilValue;
END_RCPP
}
// foo
CharacterVector foo(NumericVector object, int fmt_cur, int fmt_req);
RcppExport SEXP _Waypoint_foo(SEXP objectSEXP, SEXP fmt_curSEXP, SEXP fmt_reqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type object(objectSEXP);
    Rcpp::traits::input_parameter< int >::type fmt_cur(fmt_curSEXP);
    Rcpp::traits::input_parameter< int >::type fmt_req(fmt_reqSEXP);
    rcpp_result_gen = Rcpp::wrap(foo(object, fmt_cur, fmt_req));
    return rcpp_result_gen;
END_RCPP
}
// bar
NumericVector bar(NumericVector x, int fmt_cur, int fmt_req);
RcppExport SEXP _Waypoint_bar(SEXP xSEXP, SEXP fmt_curSEXP, SEXP fmt_reqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type fmt_cur(fmt_curSEXP);
    Rcpp::traits::input_parameter< int >::type fmt_req(fmt_reqSEXP);
    rcpp_result_gen = Rcpp::wrap(bar(x, fmt_cur, fmt_req));
    return rcpp_result_gen;
END_RCPP
}
// bas
NumericVector bas(NumericVector x, int fmt_cur, const char* what);
RcppExport SEXP _Waypoint_bas(SEXP xSEXP, SEXP fmt_curSEXP, SEXP whatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type fmt_cur(fmt_curSEXP);
    Rcpp::traits::input_parameter< const char* >::type what(whatSEXP);
    rcpp_result_gen = Rcpp::wrap(bas(x, fmt_cur, what));
    return rcpp_result_gen;
END_RCPP
}
// cla_test
int cla_test(RObject object, const char* attrname);
RcppExport SEXP _Waypoint_cla_test(SEXP objectSEXP, SEXP attrnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type object(objectSEXP);
    Rcpp::traits::input_parameter< const char* >::type attrname(attrnameSEXP);
    rcpp_result_gen = Rcpp::wrap(cla_test(object, attrname));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Waypoint_as_coords", (DL_FUNC) &_Waypoint_as_coords, 2},
    {"_Waypoint_convertcoords", (DL_FUNC) &_Waypoint_convertcoords, 2},
    {"_Waypoint_latlon", (DL_FUNC) &_Waypoint_latlon, 2},
    {"_Waypoint_validatecoords", (DL_FUNC) &_Waypoint_validatecoords, 2},
    {"_Waypoint_formatcoords", (DL_FUNC) &_Waypoint_formatcoords, 4},
    {"_Waypoint_as_waypoints", (DL_FUNC) &_Waypoint_as_waypoints, 2},
    {"_Waypoint_bin", (DL_FUNC) &_Waypoint_bin, 0},
    {"_Waypoint_foo", (DL_FUNC) &_Waypoint_foo, 3},
    {"_Waypoint_bar", (DL_FUNC) &_Waypoint_bar, 3},
    {"_Waypoint_bas", (DL_FUNC) &_Waypoint_bas, 3},
    {"_Waypoint_cla_test", (DL_FUNC) &_Waypoint_cla_test, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Waypoint(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
