# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coords <- function(nv, fmt = 1L) {
    .Call(`_Waypoint_coords`, nv, fmt)
}

`coords<-` <- function(nv, value) {
    .Call(`_Waypoint_coords_replace`, nv, value)
}

`latlon<-` <- function(nv, value) {
    .Call(`_Waypoint_latlon`, nv, value)
}

print.coords <- function(nv) {
    invisible(.Call(`_Waypoint_printcoord`, nv))
}

validate.coords <- function(nv) {
    .Call(`_Waypoint_Rvalidatecoord`, nv)
}

format.coords <- function(nv) {
    .Call(`_Waypoint_formatcoord`, nv)
}

get_deg <- function(nv) {
    .Call(`_Waypoint_get_deg`, nv)
}

get_decdeg <- function(nv) {
    .Call(`_Waypoint_get_decdeg`, nv)
}

get_min <- function(nv) {
    .Call(`_Waypoint_get_min`, nv)
}

get_decmin <- function(nv) {
    .Call(`_Waypoint_get_decmin`, nv)
}

get_sec <- function(nv) {
    .Call(`_Waypoint_get_sec`, nv)
}

waypoints <- function(df, fmt = 1L) {
    .Call(`_Waypoint_waypoints`, df, fmt)
}

`waypoints<-` <- function(df, value) {
    .Call(`_Waypoint_waypoints_replace`, df, value)
}

print.waypoints <- function(df) {
    invisible(.Call(`_Waypoint_printwaypoint`, df))
}

validate.waypoints <- function(df) {
    .Call(`_Waypoint_validatewaypoint`, df)
}

rcpp_hello_world <- function() {
    .Call(`_Waypoint_rcpp_hello_world`)
}

