# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Geographic or GPS Coordinate Class
#' 
#' @name coords
#' 
#' @description
#' \code{coords()} creates a robust representation of a series of geographic or GPS
#' coordinates instantiated as an object of class \code{"coords"}.
#' 
#' \code{coords()} and replacement form \verb{coords()<-} also convert the format of existing
#' objects of class \code{"coords"} between (i) decimal degrees, (ii) degrees and minutes, and
#' (iii) degrees, minutes and seconds.
#'
#' @details
#' Individual values provided in the \code{numeric} vector argument \code{nv} should have a decimal
#' point after the number of whole degrees in the case of \emph{decimal degrees}, after the number
#' of whole minutes in the case of \emph{degrees and minutes}, and after the number of whole
#' seconds in the case of \emph{degrees, minutes and seconds}.
#'
#' The \code{fmt} argument should be \code{1L} to represent decimal degrees, \code{2L} for degrees
#' and minutes, and \code{3L} for degrees, minutes and seconds and is used to provide both the
#' format of values in \code{numeric} vector argument \code{nv} to be converted into a
#' \code{"coords"} object and the desired format if a \code{"coords"} object is to be converted to
#' a new format. Note that on conversion of a \code{"coords"} object, the original \code{numeric}
#' vector argument \code{nv} is modified such that the values are as described in the previous
#' paragraph, and may be inspected using standard R code, see examples.
#'
#' The values of a newly created \code{"coords"} object are checked to ensure they are valid
#' geographic locations as described under \code{\link[=validate]{validate}()}. Likewise, a
#' check is made to ensure that an existing \code{"coords"} object to be converted to a new format
#' has already been validated; if not, it is re-validated. 
#'
#' @family coords_waypoints
#' @seealso
#' \code{\link[base:attr]{attr()}}, \code{\link[base:attributes]{attributes}},
#'   \code{\link[=latlon]{latlon}()}, \code{\link[base:numeric]{numeric()}} and
#'   \code{\link[=validate]{validate}()}.
#'
#' @param nv \code{numeric} vector of coordinate values, optionally named.
#'
#' @param fmt,value \code{integer}, 1L, 2L or 3L, indicating the current or desired coordinate
#'   format; default 1L.
#'
#' @param x object of class \code{"coords"} created by function \code{\link[=coords]{coords}()}.
#'
#' @param ... further arguments passed to or from other methods.
#'
#' @return
#' An object of class \code{"coords"}, comprising the original a \code{numeric} vector argument
#' \code{nv} with values possibly converted as appropriate and additional attributes: –
#' \item{\code{"fmt"}}{the coordinate format.}
#' \item{\code{"valid"}}{a \code{logical} vector indicating whether individual coordinate values
#'   are valid geographic locations.}
#'
#' @examples
#' ## Numeric vector representing degrees and minutes
#' dm <- c(5130.4659, 4932.7726, 4806.4339, 3853.3696, 0.0000, -3706.7044, -5306.2869, -2514.4093,
#'         -007.6754, 1823.9137, -12246.7203, -7702.1145, 0.0000, -1217.3178, 7331.0370, -5731.1536)
#'
#' ## Create a "coords" object of degrees and minutes
#' coords(dm, 2)
#'
#' ## Name the "coords" object
#' names(dm) <- rep(c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'                    "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport"), 2)
#' dm
#'
#' ## Convert to degrees, minutes and seconds
#' coords(dm) <- 3
#' dm
#'
#' ## Convert to decimal degrees
#' coords(dm) <- 1
#' dm
#'
#' ## Decimal degrees as a standard numeric vector
#' as.numeric(dm)
#'
#' ## Convert to degrees and minutes, and format as a character vector
#' coords(dm) <- 2
#' (dm_chr <- format(dm))
#'
#' ## Output using {base} cat()
#' cat(dm_chr, fill = 18, labels = paste0("{#", 1:16, "}:"))
#'
#' rm(dm, dm_chr)
#'
coords <- function(nv, fmt = 1L) {
    .Call(`_Waypoint_coords`, nv, fmt)
}

#' @rdname coords
`coords<-` <- function(nv, value) {
    .Call(`_Waypoint_coords_replace`, nv, value)
}

#' @title Latitude or Longitude Attribute for Coords
#' 
#' @name latlon
#'
#' @description \code{latlon()<-} adds the attribute \code{"latlon"} to objects of class
#' \code{\link[=coords]{"coords"}}, or modifies an existing \code{"latlon"} attribute.
#'
#' @details
#' Attribute \code{"latlon"} is a \code{logical} vector of length \code{1} or \code{length(cd)}
#' for which \code{TRUE} values represent latitude and \code{FALSE} values represent longitude.
#' Setting this attribute to any other length will result in an error. A \code{logical} vector of
#' length \code{1L} signifies that values are all latitude if \code{TRUE}, or all longitude if
#' \code{FALSE}.
#'
#' This attribute is used in formatting printed output and also by
#' \code{\link[=validate]{validate}()}. Indeed, the values of \code{cd} are revalidated every time
#' attribute \code{"latlon"} is added or changed.
#'
#' @seealso
#' \code{\link[=coords]{"coords"}}.
#'
#' @param cd object of class \code{\link[=coords]{"coords"}}.
#'
#' @param value a \code{logical} vector of length \code{1} or \code{length(cd)}.
#'
#' @return
#' Argument \code{cd} is returned with \code{logical} vector attribute \code{"latlon"}
#' updated as appropriate.
#'
#' @examples
#' ## Continuing example from `coords()`, named numeric vector representing degrees and minutes
#' \dontshow{
#'    dm <-
#'        c(5130.4659, 4932.7726, 4806.4339, 3853.3696, 0.0000, -3706.7044, -5306.2869, -2514.4093,
#'		   -007.6754, 1823.9137, -12246.7203, -7702.1145, 0.0000, -1217.3178, 7331.0370, -5731.1536)
#'
#'    names(dm) <- 
#'        rep(c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'              "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport"), 2)
#' }
#'
#' ## Create "coords" object of degrees and minutes
#' coords(dm) <- 2
#'
#' ## Set "latlon" attribute to FALSE, length 1
#' latlon(dm) <- FALSE
#' dm
#'
#' ## Set "latlon" attribute to TRUE and FALSE (each n=8)
#' latlon(dm) <- rep(c(TRUE, FALSE), each = 8)
#' dm
#'
#' ## Reversing latitude and longitude results in an
#' ## invalid latitude value and a warning
#' latlon(dm) <- rep(c(FALSE, TRUE), each = 8)
#' dm
#'
#' rm(dm)
#'
`latlon<-` <- function(cd, value) {
    .Call(`_Waypoint_latlon`, cd, value)
}

#' @title Validate Coords or Waypoints
#' 
#' @name validate
#' 
#' @description
#' \code{validate()} validate objects of class \code{"coords"} or \code{"waypoints"}.
#'
#' @details
#' Individual coordinate values within \code{\link[=coords]{"coords"}} or
#' \code{\link[=waypoints]{"waypoints"}} objects are validated to ensure their being plausible
#' geographic locations.
#'
#' To be valid, the absolute values of coordinates in degrees must not exceed 180, or 90 if degrees
#' of latitude and, similarly, the absolute values of the minutes and seconds components, where
#' given, must not exceed 60 degrees. Otherwise a warning will be issued and the \code{"valid"}
#' attribute in the case of a \code{"coords"} object, or \code{"validlat"} and \code{"validlon"}
#' attributes in the case of a \code{"waypoints"} object will be set to \code{FALSE} for any
#' non-compliant coordinate values.
#'
#' @seealso
#' \code{\link[=coords]{"coords"}} and \code{\link[=waypoints]{"waypoints"}}.
#'
#' @param x object of class \code{"coords"} or \code{"waypoints"}.
#'
#' @param ... further arguments passed to or from other methods.
#'
#' @return
#' \code{validate()} returns its argument with \code{logical} vector attribute \code{"valid"},
#' or attributes \code{"validlat"} and \code{"validlon"} updated as appropriate for
#' \code{"coords"} and' \code{"waypoints"} objects respectively.
#'
#' @examples
#' ## Continuing example from `coords()`, named numeric vector representing degrees and minutes
#' \dontshow{
#'    dm <-
#'        c(5130.4659, 4932.7726, 4806.4339, 3853.3696, 0.0000, -3706.7044, -5306.2869, -2514.4093,
#'		   -007.6754, 1823.9137, -12246.7203, -7702.1145, 0.0000, -1217.3178, 7331.0370, -5731.1536)
#'
#'    names(dm) <- 
#'        rep(c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'              "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport"), 2)
#' }
#'
#' ## Create "coords" object of degrees and minutes
#' coords(dm) <- 2
#'
#' validate(dm)
#'
#' ## Change first value to have more than 60 minutes
#' dm[1] <- 5160.4659
#'
#' validate(dm)
#'
#' ## Examine "valid" attribute of dm
#' attr(dm, "valid")
#'
#' ###
#' ## Continuing example from `waypoints()`, data frame representing waypoint names and latitude
#' ## and longitude values in decimal degrees
#' \dontshow{
#' wp1 <- data.frame(
#'     name = c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'              "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport"),
#'     lat = c(51.507765, 49.54621, 48.107232, 38.889494, 0, -37.11174, -53.104781, -25.240156),
#'     lon = c(-0.127924, 18.398562, -122.778671, -77.035242, 0, -12.28863, 73.517283, -57.519227)
#' )
#' }
#'
#' ## Create "waypoints" object of decimal degrees
#' waypoints(wp1) <- 1
#'
#' validate(wp1)
#'
#' ## Change penultimate latitude absolute value to have more than 90 degrees
#' wp1$lat[7] <- -93.104781
#'
#' validate(wp1)
#'
#' ## Examine "validlat" attribute of wp1
#' attr(wp1, "validlat")
#'
#' rm(dm, wp1)
#'
validate.coords <- function(x, ...) {
    .Call(`_Waypoint_validatecoords`, x)
}

#' @rdname coords
format.coords <- function(x, ...) {
    .Call(`_Waypoint_formatcoords`, x)
}

#' @rdname coords
print.coords <- function(x, ...) {
    invisible(.Call(`_Waypoint_printcoords`, x))
}

#' @title Geographic or GPS Waypoint Class
#' 
#' @name waypoints
#' 
#' @description
#' \code{waypoints()} creates a robust representation of a series of geographic or GPS waypoints
#' instantiated as an object of class \code{"waypoints"}.
#' 
#' \code{waypoints()} and replacement form \verb{waypoints()<-} also convert the format of
#' existing objects of class \code{"waypoints"} between (i) decimal degrees, (ii) degrees and
#' minutes, and (iii) degrees, minutes and seconds.
#'
#' @details
#' By default, the names of the waypoints should be included in a "Name" column of data frame
#' argument \code{df}, and the latitude and longitude in the two columns immediately on the right
#' hand side of "Name". An alternative column for waypoint names may be specified by setting an
#' \code{integer} attribute, \code{"namescol"} indicating its position in \code{df}, while setting
#' this attribute to \code{NA} supresses printing of waypoint names. If \code{df} has neither a
#' "Name" column nor a \code{"namescol"} attribute, the \code{"row.names"} attribute is used for
#' waypoint names if present in \code{df}. Similarly, alternative columns for the latitude and
#' longitude may be specified by setting \code{"llcols"} as a length 2 \code{integer} vector
#' attribute indicating their positions in \code{df}.
#'
#' Individual values provided in the \code{numeric} vector latitude and longitude columns of data
#' frame argument \code{df} should have a decimal point after the number of whole degrees in the
#' case of \emph{decimal degrees}, after the number of whole minutes in the case of
#' \emph{degrees and minutes}, and after the number of whole seconds in the case of
#' \emph{degrees, minutes and seconds}.
#'
#' The \code{fmt} argument should be \code{1L} to represent decimal degrees, \code{2L} for degrees
#' and minutes, and \code{3L} for degrees, minutes and seconds and is used to provide both the
#' format of values in data frame argument \code{df} to be converted into a \code{"waypoints"}
#' object and the desired format if a \code{"waypoints"} object is to be converted to a new format.
#' Note that on conversion of a \code{"waypoints"} object, the original data frame argument
#' \code{df} is modified such that the latitude and longitude values are as described in the
#' previous paragraph, and may be inspected using standard R code, see examples.
#'
#' The latitude and longitude values of a newly created \code{"waypoints"} object are checked to
#' ensure they are valid geographic locations as described under
#' \code{\link[=validate]{validate}()}. Likewise, a check is made to ensure that an existing
#' \code{"waypoints"} object to be converted to a new format has already been validated; if not, it
#' is re-validated. 
#'
#' @family coords_waypoints
#' @seealso
#' \code{\link[base:attr]{attr()}}, \code{\link[base:attributes]{attributes}},
#'   \code{\link[base:data.frame]{data.frame()}}, and \code{\link[=validate]{validate}()}.
#'
#' @param df a data frame with each row representing a waypoint, comprising at least two
#'   \code{numeric} columns containing values of latitude and longitude, and optionally a
#'   \code{character} column of waypoint names (see \emph{Details}). 
#'
#' @param fmt,value an \code{integer} of value 1L, 2L or 3L, indicating the current or desired
#'   coordinate format (see \emph{Details}); default 1L.
#'
#' @param x an object of class \code{"waypoints"} created by function
#' \code{\link[=waypoints]{waypoints}()}.
#'
#' @param ... further arguments passed to or from other methods.
#'
#' @return
#' An object of classes \code{"waypoints"} and \code{"data.frame"}, comprising the original data
#' frame argument \code{df}, with latitude and longitude values possibly converted as appropriate
#' and additional attributes: –
#' \item{\code{"fmt"}}{the coordinate format.}
#' \item{\code{"namescol"}}{the position of waypoint names, if present within \code{df}.}
#' \item{\code{"llcols"}}{the position of latitude and longitude columns within \code{df}.}
#' \item{\code{"validlat"} and \code{"validlon"}}{\code{logical} vectors indicating whether
#'   individual latitude and longitude values are valid geographic locations.}
#'
#' @examples
#' ## Dataframe representing waypoint names, and latitude and longitude values
#' ## of degrees, minutes and seconds
#' wp1 <- data.frame(
#'     name = c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'              "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport"),
#'     lat = c(513027.95, 493246.36, 480626.04, 385322.18, 0, -370642.26, -530617.21, -251424.56),
#'     lon = c(-00740.53, 182354.82, -1224643.22, -770206.87, 0, -121719.07, 733102.22, -573109.21)
#' )
#'
#' ## Create "waypoints" object of degrees, minutes and seconds (fmt = 3)
#' waypoints(wp1, 3)
#'
#' ## Convert to degrees and minutes (fmt = 2)
#' waypoints(wp1) <- 2
#' wp1
#'
#' ## Convert to decimal degrees (fmt = 1)
#' waypoints(wp1) <- 1
#' wp1
#'
#' ###
#' ## Dataframe representing unnamed latitude and longitude values in decimal degrees
#' wp2 <- data.frame(
#'     lat = c(51.507765, 49.54621, 48.107232, 38.889494, 0, -37.11174, -53.104781, -25.240156),
#'     lon = c(-0.127924, 18.398562, -122.778671, -77.035242, 0, -12.28863, 73.517283, -57.519227)
#' )
#'
#' ## Create "waypoints" object of decimal degrees (default fmt = 1)
#' waypoints(wp2)
#'
#' ## Add row.names
#' row.names(wp2) <-
#'     c("Nelson's Column", "Ostravice", "Tally Ho", "Washington Monument", "Null Island",
#'       "Tristan da Cunha", "Mawson Peak", "Silvio Pettirossi International Airport")
#' wp2
#'
#' ## Convert to degrees and minutes (fmt = 2)
#' waypoints(wp2) <- 2
#' wp2
#'
#' ## Convert to degrees, minutes and seconds (fmt = 3)
#' waypoints(wp2) <- 3
#' wp2
#'
#' ## Degrees, minutes and seconds as a standard data frame
#' as.data.frame(wp2)
#'
#' ## Convert to decimal degrees, and format as a character vector
#' waypoints(wp2) <- 1
#' (wp2_chr <- format(wp2))
#'
#' ## Output using {base} cat()
#' cat(wp2_chr, fill = 26, labels = paste0("{#", 1:8, "}:"))
#'
#' rm(wp1, wp2)
#'
waypoints <- function(df, fmt = 1L) {
    .Call(`_Waypoint_waypoints`, df, fmt)
}

#' @rdname waypoints
`waypoints<-` <- function(df, value) {
    .Call(`_Waypoint_waypoints_replace`, df, value)
}

#' @rdname validate
validate.waypoints <- function(x, ...) {
    .Call(`_Waypoint_validatewaypoints`, x)
}

#' @rdname waypoints
format.waypoints <- function(x, ...) {
    .Call(`_Waypoint_formatwaypoints`, x)
}

#' @rdname waypoints
print.waypoints <- function(x, ...) {
    invisible(.Call(`_Waypoint_printwaypoints`, x))
}

as_coord <- function(df, latlon) {
    .Call(`_Waypoint_as_coord`, df, latlon)
}

